parameters:
  - name: language
    type: string
    values:
        - java
        - python
  - name: packaging
    type: string
    values:
        - library
        - docker
  - name: artifactsFeeds
    type: string
    default: 'DIN-SSDE'
  - name: containerRegistry
    type: string
    default: 'DIN-SSDE'
  - name: imageName
    type: string
    default: 'DIN-SSDE'

variables:
  - name: isPullRequest
    value: $[eq(variables['Build.Reason'], 'PullRequest')]
  - name: isMainBranch
    value: $[eq(variables['Build.SourceBranchName'], 'main')]

stages: 
    - stage: Initialize
      jobs:
        - job: showVars
          steps:
            - script: |
                echo $(isPullRequest)
                echo $(Build.SourceBranchName)
                echo $(isMainBranch)
    - stage: Test
      dependsOn: Initialize
      condition: and(succeeded(), eq(variables.isPullRequest, 'true'))
      jobs:
        - template: java/test.yml
    - stage: Quality
      dependsOn: Initialize
      condition: and(succeeded(), eq(variables.isMainBranch, 'true'))
      jobs:
        - template: java/quality.yml
    - stage: Deliver
      dependsOn: Initialize
      condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
      jobs:
        - template: java/deliver.yml
          parameters:
              packaging: ${{parameters.packaging}}
              artifactsFeeds: ${{parameters.artifactsFeeds}}
              containerRegistry: ${{parameters.containerRegistry}}
              imageName: ${{parameters.imageName}}