
parameters:
  - name: mvnOpts
    type: string
    default: ''
  - name: artifactsFeeds
    type: string
    default: 'DIN-SSDE'



jobs:
  - job: SonarQube
    steps:
      - template: mavenCache.yml
      - script: echo $(System.TeamProject)
  - job: Coverage
    steps:
      - template: mavenCache.yml
      - template: mavenAuthenticate.yml
        parameters:
          artifactsFeeds: ${{parameters.artifactsFeeds}}
      - task: SonarQubePrepare@4
        inputs:
          SonarQube: 'SonarQube'
          scannerMode: 'Other'
          extraProperties: |
            # Additional properties that will be passed to the scanner, 
            # Put one key=value per line, example:
            sonar.projectKey=$(System.TeamProject)_$(System.TeamProject)
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          codeCoverageToolOption: 'JaCoCo'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: true
          isJacocoCoverageReportXML: true
          sqMavenPluginVersionChoice: 'pom'
      - task: SonarQubePublish@4
        inputs:
          pollingTimeoutSec: '300'
